#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /user
    controller: App\Controller\DefaultController::index

app_login:
    path: /login
    controller: App\Controller\SecurityController:login
