#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\IndexController::index

app_login:
    path: /login
    controller: App\Controller\SecurityController:login

app_register:
    path: /register
    controller: App\Controller\SecurityController:register

app_logout:
    path: /logout
    controller: App\Controller\SecurityController:logout

admin_index:
    path: /admin
    controller: App\Controller\Admin\DashboardController:index

user_profile:
    path: /profile
    controller: App\Controller\UserController:profile
