#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\IndexController::index

app_login:
    path: /login
    controller: App\Controller\AuthController:login

app_register:
    path: /register
    controller: App\Controller\AuthController:register

app_activate_profile:
    path: /activateprofile/{hash}
    controller: App\Controller\AuthController:activateProfile

app_logout:
    path: /logout
    controller: App\Controller\SecurityController:logout

admin_index:
    path: /admin
    controller: App\Controller\Admin\DashboardController:index

profile_index:
    path: /profile
    controller: App\Controller\Front\ProfileController:index
